#158456314 Implement Travis Continuous Integration
andela/hc-wits-kla pull request #1
Opened 2018-06-20 11:37 UTC by RrNn

### What does this PR do?
- Integrate Continuous integration using Travis and test coverage using Coveralls
- Show the badges in the readme, for Travis CI and Coveralls
### Relevant pivotaltracker story
[#157273805](https://www.pivotaltracker.com/n/projects/158456314)

2018-06-20 14:01 UTC, solnsubuga approved these changes
LGTM

2018-06-20 17:03 UTC, wasswa-derick reviewed
- 'hc-venv' in the gitignore, you can consider opening your project at the root of hc-wits-kla, that way, the virtual environment folder won't even be tracked.
- Or you can consider using virtualenvwrapper. It allows to create various virtual environments and switch between them anywhere, hence there will be no need to track it in gitignore.

2018-06-20 17:03 UTC, wasswa-derick approved these changes

2018-06-20 17:25 UTC, ghost commented
Good work

2018-06-20 17:27 UTC, Yiga-fred approved these changes

2018-06-20 17:27 UTC, Yiga-fred approved these changes
Good work

2018-06-21 06:11 UTC, john555 requested changes
Overall, PR looks good.

2018-06-21 06:11 UTC, john555 commented on .gitignore
> +.vscode/
Add a new line at the end of this file.

2018-06-21 12:54 UTC, RrNn commented on .gitignore
> +.vscode/
Okay, I'm gonna do that

2018-06-22 15:06 UTC, john555 commented
Resolve conflicts on your PR.

2018-06-25 10:59 UTC, john555 approved these changes

2018-06-25 11:00 UTC, merged