Ch apitests
andela/hc-wits-kla pull request #3
Opened 2018-06-21 10:14 UTC by wasswa-derick

#### What does this PR do?
#[158175309] Have API tests get fixed
#### Description of Task to be completed?
* Have reviews when creating checks work
* Have assertions and tests for listing checks work
* Have assertions and tests for badges work

#### How should this be manually reviewed?
- For the tests and assertions, I finished I have included **DONE* on their comments.

2018-06-21 12:58 UTC, john555 commented
Resolve merge conflicts.

2018-06-21 13:45 UTC, john555 commented
Your PR title does not match the style guide.

2018-06-22 14:55 UTC, john555 requested changes

2018-06-22 14:55 UTC, john555 commented on hc/api/tests/test_admin.py
> +        ### Set Alice to be staff and superuser and save her :) -- DONE
Get rid of the -- DONE

2018-06-22 14:55 UTC, john555 commented on hc/api/tests/test_badge.py
> +        assert r.status_code == 400
You should use `self.assertEqual`. e.g `self.assertEqual(400, r.status_code)`. Note that it's common and a best practice to start with the expected value followed by the returned value. https://stackoverflow.com/questions/9331259/unit-testing-why-is-the-expected-argument-always-first-in-equality-tests

2018-06-22 14:57 UTC, john555 commented
Squash your commits. Ther should be atmost 3.

2018-06-22 17:26 UTC, RrNn commented
It looks good to me, just that the PT id doesn't lead me to the PT story directly.. perhaps make it a link

2018-06-22 17:56 UTC, john555 commented
Your commit messages are not up to standard.  'Fix API tests' would be a much better one.

2018-06-22 18:00 UTC, john555 commented
Rebase your branch.

2018-06-23 22:11 UTC, solnsubuga commented on hc/api/tests/test_ping.py
> +        self.assertEqual(400, r.status_code)
Is this change necessary? I think the old line and new line achieve the same thing.

2018-06-23 22:13 UTC, solnsubuga approved these changes
LGTM

2018-06-25 09:24 UTC, wasswa-derick commented on hc/api/tests/test_ping.py
> +        self.assertEqual(400, r.status_code)
Hey Solomon, the TTL suggests I use assertEqual because it is a best practice to have the expected value first then what comes from the service next.

2018-06-25 12:02 UTC, john555 approved these changes

2018-06-25 12:04 UTC, merged