[Feature #158175314] Render a Failed Jobs Tab
andela/hc-wits-kla pull request #7
Opened 2018-06-27 10:12 UTC by wasswa-derick

#### What does this PR do?
* Renders an Authorized User's Unresolved Checks

#### Description of Task to be completed?
* Add tab to the Base User Page
* Create Page for Failing Checks ([Feature #158175314] Add Failed check tab and custom page)
* Retrieve all the Authorized User's Failing checks ([Feature #158175314] Render failed checks on the unresolved stuff tab)

#### How should this be manually tested?
- Clone the project from GitHub ```git clone https://github.com/andela/hc-wits-kla.git```
- After cloning, cd into the project directory and run the environment setup in the project README
- Run the project URL from the terminal console in your browser
- Create an Account and Login
- Add some checks, ping some of the checks, adjust the period and grace period to a lower time to have the check drop
- When the check drops, an alert is sent to the user and the check is added to the Failed Checks Tab

#### Any background context you want to provide?
- When the difference between the time now and the and a summation of the check's last ping, period and grace periods is positive then the check is down and an email alert is sent to the owner.

#### What are the relevant pivotal tracker stories?
* #158175314

2018-06-27 11:06 UTC, john555 commented
Add a screenshot in your PR.

2018-06-27 11:19 UTC, john555 requested changes

2018-06-27 11:19 UTC, john555 commented on templates/front/failed_checks.html
> +                        <div class="form-group">
Fix indentation.

2018-06-27 11:21 UTC, john555 commented
Are there any dependencies that you forgot to add in the requirements.txt file? I am failing to run the app on your branch.

2018-06-27 13:31 UTC, ja-odur commented on hc/front/tests/test_my_failed_checks.py
> +        self.assertEqual("down", self.check.status)
add a new line at the end of this file

2018-06-27 17:26 UTC, Yiga-fred commented
Good work @wasswa-derick  looking good.

2018-06-29 05:41 UTC, john555 approved these changes

2018-06-29 05:42 UTC, merged